## build the docker code 
## push the dockerimage to socker hub 
## ssh itno our vm and start the new image

name: Deploy the backend
on: 
  push:
    branches: [main]
jobs:
  build:
    runs-on: ununtu-latest
    steps:
      - name: Check out the code 
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2 #docker login
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    
      - name: Build and push Docker image # docker build and push to docker hub
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./docker/dockerfile.backend
          push: true
          tags: amaxn007/todo-app-backend:${{ github.sha }}

          ## step to deploy this to vm after above step is done

      - name: SSH and deploy to VM
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.VM_IP }}
          username: ${{ secrets.VM_USERNAME }}
          key: ${{ secrets.VM_SSH_KEY }}
          script: |
            docker pull asustodoapp/backend:latest
            docker stop backend || true
            docker rm backend || true
            docker run -d --name backend -p 8080:8080 --env DATABASE_URL=${{ secrets.DATABASE_URL }} asustodoapp/backend:latest